2024-11-20 10:30:20 - Server listening on ('0.0.0.0', 31026)
2024-11-20 10:30:20 - Main thread: before accepting ...
2024-11-20 10:30:25 - New Client number 1 from ('127.0.0.1', 50953)
2024-11-20 10:30:45 - Client 1 Exit
2024-11-20 10:51:57 - Server listening on ('0.0.0.0', 31026)
2024-11-20 10:52:02 - Main thread: before accepting ...
2024-11-20 10:52:12 - New Client number 1 from ('127.0.0.1', 51376)
2024-11-20 11:22:39 - Server listening on ('0.0.0.0', 31026)
2024-11-20 11:22:39 - Main thread: before accepting ...
2024-11-20 11:22:49 - New Client number 1 from ('127.0.0.1', 51477)
2024-11-20 11:24:46 - New Client number 2 from ('172.16.12.21', 49905)
2024-11-20 11:30:31 - Client 2 Exit
2024-11-20 11:42:20 - Client 1 Exit
2024-11-20 12:59:54 - Server listening on ('0.0.0.0', 31026)
2024-11-20 12:59:55 - Main thread: before accepting ...
2024-11-20 13:00:03 - New Client number 1 from ('127.0.0.1', 51825)
2024-11-20 13:11:51 - Server listening on ('0.0.0.0', 31026)
2024-11-20 13:11:52 - Main thread: before accepting ...
2024-11-20 13:11:53 - New Client number 1 from ('127.0.0.1', 51902)
2024-11-20 16:19:42 - Server listening on ('0.0.0.0', 31026)
2024-11-20 16:19:43 - Main thread: before accepting ...
2024-11-20 16:19:47 - New Client number 1 from ('127.0.0.1', 50171)
2024-11-20 16:48:27 - Client 1 Exit
2024-11-20 16:48:44 - New Client number 2 from ('127.0.0.1', 50796)
2024-11-20 16:51:58 - Server listening on ('0.0.0.0', 31026)
2024-11-20 16:51:58 - Main thread: before accepting ...
2024-11-20 16:51:59 - New Client number 1 from ('127.0.0.1', 50971)
2024-11-20 16:52:14 - Traceback (most recent call last):
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\server.py", line 453, in protocol_build_reply
    elif (not cr.is_dir_owner(clients[tid].id, fields[2])):
                                               ~~~~~~^^^
IndexError: list index out of range
2024-11-20 16:55:13 - Server listening on ('0.0.0.0', 31026)
2024-11-20 16:55:13 - Main thread: before accepting ...
2024-11-20 16:55:17 - Server listening on ('0.0.0.0', 31026)
2024-11-20 16:55:17 - Main thread: before accepting ...
2024-11-20 16:55:28 - New Client number 1 from ('127.0.0.1', 51075)
2024-11-20 16:55:48 - Traceback (most recent call last):
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\server.py", line 463, in protocol_build_reply
    name = cr.get_file_sname(file_id)
                             ^^^^^^^
UnboundLocalError: cannot access local variable 'file_id' where it is not associated with a value
2024-11-20 16:56:34 - Server listening on ('0.0.0.0', 31026)
2024-11-20 16:56:34 - Main thread: before accepting ...
2024-11-20 16:57:01 - New Client number 1 from ('127.0.0.1', 51145)
2024-11-20 16:57:12 - Traceback (most recent call last):
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\server.py", line 464, in protocol_build_reply
    if os.path.exists(cloud_path + "\\" + name):
                      ~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "NoneType") to str
2024-11-20 16:57:43 - Traceback (most recent call last):
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\server.py", line 464, in protocol_build_reply
    if os.path.exists(cloud_path + "\\" + name):
                      ~~~~~~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\server.py", line 807, in handle_request
    to_send = protocol_build_reply(request, tid, sock)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\server.py", line 481, in protocol_build_reply
    throw_file(sock, tid)
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\server.py", line 113, in throw_file
    raise Exception
Exception
2024-11-20 16:57:44 - Client 1 Exit
2024-11-20 16:57:44 - New Client number 2 from ('127.0.0.1', 51181)
2024-11-20 17:01:47 - Server listening on ('0.0.0.0', 31026)
2024-11-20 17:01:47 - Main thread: before accepting ...
2024-11-20 17:01:54 - New Client number 1 from ('127.0.0.1', 51259)
2024-11-20 17:02:17 - Traceback (most recent call last):
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\modules\client_requests.py", line 581, in clean_db
    os.remove(server_path + "\\cloud\\" + name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\idanh\\desktop\\Cyber\\My Projects\\Final Project\\Main\\server\\cloud\\68ffb6400c894254a1dfab5c0d3a54b0.lock'
2024-11-20 17:02:47 - Traceback (most recent call last):
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\modules\client_requests.py", line 581, in clean_db
    os.remove(server_path + "\\cloud\\" + name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\idanh\\desktop\\Cyber\\My Projects\\Final Project\\Main\\server\\cloud\\68ffb6400c894254a1dfab5c0d3a54b0.lock'
2024-11-20 17:02:57 - Server listening on ('0.0.0.0', 31026)
2024-11-20 17:02:57 - Main thread: before accepting ...
2024-11-20 17:02:59 - New Client number 1 from ('127.0.0.1', 51303)
2024-11-20 17:03:30 - Client 1 Exit
2024-11-20 17:03:31 - New Client number 2 from ('127.0.0.1', 51310)
2024-11-20 17:05:51 - Traceback (most recent call last):
  File "c:\Users\idanh\desktop\Cyber\My Projects\Final Project\Main\server\modules\client_requests.py", line 581, in clean_db
    os.remove(server_path + "\\cloud\\" + name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\idanh\\desktop\\Cyber\\My Projects\\Final Project\\Main\\server\\cloud\\7f382a3e94e74c5c802be3591c229476.lock'
2024-11-20 17:06:11 - Server listening on ('0.0.0.0', 31026)
2024-11-20 17:06:11 - Main thread: before accepting ...
2024-11-20 17:06:17 - New Client number 1 from ('127.0.0.1', 51372)
2024-11-20 17:06:38 - Client 1 Exit
2024-11-20 17:06:38 - New Client number 2 from ('127.0.0.1', 51379)
